### ISSUE TITLE
Fix code scanning alert - Use of password hash with insufficient computational effort

### ISSUE THREAD

**Issue by Luuuuuis** [EffnerAppArchive/effnerapp-web-legacy#179]
Switch hashing algorithm to bcrypt?

https://security.stackexchange.com/questions/133239/what-is-the-specific-reason-to-prefer-bcrypt-or-pbkdf2-over-sha256-crypt-in-pass

Tracking issue for:
- [ ] https://github.com/EffnerApp/EffnerApp/security/code-scanning/1

**Comment by sebiIO** [comment]
outdated version, moving issue to new repo
